### ISSUE TITLE
Reopen for polls

### ISSUE THREAD

**Issue by rainbowdashlabs** [JohnnyJayJay/instant-poll#47] opened 2023-08-09 13:56 UTC
Would be nice to be able to reopen polls which have no time limit or havent reached the time limit yet c:
Especially if people press the close button by accident too early

**Comment by JohnnyJayJay** [comment] 2023-08-09 14:15
duplicate of #48 (pretty much)

I think I wouldn't like to restrict this based on automatic closing.

**Closed as not planned** 2023-08-09 14:15 UTC
